name: Merge babysitter
on:
    pull_request:
        types:
        - labeled
        - opened
        - synchronize
        - review_request_
        - auto_merge_enabled
jobs:
    merge_or_rebase:
        runs-on: ubuntu-latest
        steps:
            - name: Set the auto-merge or rebase the PR
              uses: lukaszachy/merge-babysitter-action@v1
              env:
                GH_TOKEN: ${{ github.token }}
                REPO: "lukaszachy/playground-repo"
