name: Attempt

on:
    - pull_request
    - push
    - label
    
    
    
jobs:
    letsee:
        runs-on: ubuntu-latest

        steps:
            - name: Hmm
              uses: lukaszachy/action-repo@v1
              env:
                GH_TOKEN: ${{ github.token }}
                REPO: "lukaszachy/playground-repo"
