name: Merge babysitter
on:
    pull_request:
        types:
        - labeled
        - opened
        - synchronize
        - review_request_
        - auto_merge_enabled
jobs:
    letsee:
        runs-on: ubuntu-latest
        steps:
            - name: Rebase and/or auto merge
              uses: lukaszachy/action-repo@v1
              env:
                GH_TOKEN: ${{ github.token }}
                REPO: "lukaszachy/playground-repo"
