name: Attempt

on:
    pull_request:
        types:
        - labeled
        - opened
    push
    label
    
    
    
jobs:
    letsee:
        runs-on: ubuntu-latest

        steps:
            - name: Hmm
              uses: lukaszachy/action-repo@v1
